server.port=8084

# ============================================================
# DATASOURCE (SUPABASE SESSION POOLER IPv4)
# ============================================================
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.jnkpuplzqnmejirmyvye
spring.datasource.password=c0m3rc14lH1br1d02026*-+
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# DESACTIVAR FLYWAY
spring.flyway.enabled=false

# ============================================================
# IA GRATUITA (GROQ)
# ============================================================
openai.api-base-url=https://api.groq.com/openai/v1
openai.api-key=${OPENAI_API_KEY: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}
openai.model=openai/gpt-oss-20b


# ============================================================
# WHATSAPP
# ============================================================
whatsapp.api-base-url=https://graph.facebook.com/v20.0
whatsapp.phone-number-id=1333592066495703
whatsapp.access-token=EAArV2ENFyYIBSQ3JAjjDA9KOuuSGCI6VVaOgZC1tRwMhZC0EDG6lIwPDbQjdlD7WbnZA1GJPvsUNR76ZB1xI9TqUy7OnpJHXaHilnvYpZCH2TSa0fn7TwqRsQmovZC4MpMRYNG1n2pIsXZBcuVAyB4eTCeuPTMZBekjHj3s2GxAW6g8nbiw0KOViRRBzdswn6f6OojMF5tEhuJOkrDrX71LqLCgyjrBLItU5fXs979qkeCxvfk0kGZA2c7Vs0KPpZAyXr7fPuidhlPB30JDj3CAgZDZD
whatsapp.webhook-verify-token=mi_token_secreto_123

# ============================================================
# AGENT WORKER 24/7
# ============================================================
spring.task.scheduling.pool.size=2
agent.worker-fixed-delay-ms=1000
agent.max-attempts=3
agent.retry-base-seconds=5
agent.stale-job-minutes=5


# ============================================================
# HIKARICP OPTIMIZADO PARA SUPABASE POOLER
# ============================================================
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=3000
